name: Reusable workflow example

on:
  workflow_call:
    inputs:
      name:
        description: 'Name'
        required: true
        type: string
        default: 'test callee'
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        type: string
        default: 'test callee'
      
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
        - name: Hello world
          run: echo "Hello ${{ github.event.inputs.name }}"
