name: Reusable workflow example

on:
  workflow_call:
    inputs:
      name:
        description: 'Name'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        type: string
      
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
        - name: Hello world
          run: echo "Hello ${{ inputs.name }}"
